default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: LinkedTeamDevelopment

test:
  <<: *default
  database: LinkedTeamTest

production:
  <<: *default
  database: LinkedTeamProduction
